DROP TABLE t_docs_grau CASCADE CONSTRAINTS;
DROP TABLE t_telefone CASCADE CONSTRAINTS;
DROP TABLE t_docente CASCADE CONSTRAINTS;
DROP TABLE t_aluno CASCADE CONSTRAINTS;
DROP TABLE t_pessoa CASCADE CONSTRAINTS;
DROP TABLE t_instituicao CASCADE CONSTRAINTS;

DROP SEQUENCE seq_pessoa_pk;

